[package]
authors = ["Bhumin Bhandari <bhandaribhumin@gmail.com>"]
edition = "2018"
name = "rusty-bunny"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
percent-encoding = "2.1.0"
rocket = "0.4.4"
